name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]  # triggers whenever you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Install dependencies
      - run: npm ci

      # 4. Build Next.js project
      - run: npm run build   # generates 'out/' automatically because of output: 'export'

      # 5. Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # automatically provided by GitHub
          publish_dir: ./out
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'